import { Link } from "@tanstack/react-router";
import { ArrowRight, Camera, ChevronRight, CircleDollarSign, Gamepad2, Heart, Leaf, MessageSquareQuote, PencilLine, ShieldCheck, Star, TentTree, Trophy, Wrench, Zap } from "lucide-react";
import drillImage from "@/assets/listing-drill.jpg";
import campingImage from "@/assets/listing-camping.jpg";
import cameraImage from "@/assets/listing-camera.jpg";
import mixerImage from "@/assets/listing-mixer.jpg";
import { Container, Section } from "@/components/layout/container";
import { BrandLogo } from "@/components/brand/brand-logo";
import { HeroCarousel } from "@/components/home/hero-carousel";
import { SiteHeader } from "@/components/navigation/site-header";
import { Button } from "@/components/ui/button";

const categories = [{ label: "Tools", icon: Wrench }, { label: "Electronics", icon: Zap }, { label: "Camping", icon: TentTree }, { label: "Photography", icon: Camera }, { label: "Sports", icon: Trophy }, { label: "Events", icon: Gamepad2 }];
const listings = [
  { id: "cordless-drill-kit", title: "Cordless drill kit", image: drillImage, price: "$12", location: "0.8 mi" },
  { id: "camping-tent", title: "4-person camping set", image: campingImage, price: "$24", location: "1.2 mi" },
  { id: "mirrorless-camera", title: "Mirrorless camera kit", image: cameraImage, price: "$38", location: "1.6 mi" },
  { id: "stand-mixer", title: "Professional stand mixer", image: mixerImage, price: "$16", location: "2.1 mi" },
];

export function HomePage() {
  return <div className="min-h-screen overflow-hidden bg-background">
    <SiteHeader />
    <HeroCarousel />

    

    <Section><Container><SectionHeading eyebrow="Find your thing" title="A little less buying. A lot more doing." link="/categories" /><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">{categories.map(({ label, icon: Icon }) => <Link key={label} to="/categories" className="premium-lift group rounded-2xl border border-border/70 bg-card p-5 hover:border-highlight"><span className="grid size-11 place-items-center rounded-xl bg-muted text-primary transition-colors group-hover:bg-highlight"><Icon className="size-5" /></span><h3 className="mt-5 font-display text-lg font-bold">{label}</h3><p className="mt-1 flex items-center gap-1 text-xs text-muted-foreground">Explore <ChevronRight className="size-3 transition-transform group-hover:translate-x-1" /></p></Link>)}</div></Container></Section>

    <Section className="bg-muted/55"><Container><SectionHeading eyebrow="Around the corner" title="Popular near you" link="/explore" /><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{listings.map((item) => <Link key={item.id} to="/item/$id" params={{ id: item.id }} className="group min-w-0"><div className="relative overflow-hidden rounded-2xl bg-card"><img src={item.image} alt={item.title} width={768} height={768} loading="lazy" className="aspect-square w-full object-cover transition-transform duration-500 group-hover:scale-[1.04]" /><span className="absolute right-3 top-3 grid size-10 place-items-center rounded-full bg-card/90 shadow-subtle backdrop-blur"><Heart className="size-5" /></span></div><div className="pt-4"><h3 className="min-w-0 truncate font-display text-lg font-bold">{item.title}</h3><p className="mt-1 text-sm text-muted-foreground">{item.location} away</p><p className="mt-2"><strong className="font-display text-lg">{item.price}</strong><span className="text-sm text-muted-foreground"> / day</span></p></div></Link>)}</div></Container></Section>

    <Section><Container><div className="grid gap-12 lg:grid-cols-[0.75fr_1.25fr] lg:items-start"><div className="lg:sticky lg:top-28"><p className="text-sm font-bold uppercase tracking-[0.18em] text-secondary">Simple by design</p><h2 className="mt-3 text-4xl font-bold tracking-tight sm:text-5xl">From “I need one” to “all done.”</h2><p className="mt-5 max-w-md leading-7 text-muted-foreground">Borrow in four straightforward steps, with clear communication at every point.</p><Button asChild className="mt-7" variant="highlight"><Link to="/how-it-works">How it works <ArrowRight /></Link></Button></div><ol className="grid gap-4 sm:grid-cols-2">{[["01","Find","Search useful things near you."],["02","Reserve","Choose your dates and send a request."],["03","Use","Meet nearby and enjoy what you borrowed."],["04","Return","Bring it back and share a quick review."]].map(([number,title,copy]) => <li key={number} className="rounded-3xl border border-border bg-card p-6 shadow-subtle"><span className="font-display text-sm font-bold text-secondary">{number}</span><h3 className="mt-10 text-2xl font-bold">{title}</h3><p className="mt-2 leading-6 text-muted-foreground">{copy}</p></li>)}</ol></div></Container></Section>

    <Section className="bg-primary text-primary-foreground"><Container><div className="grid gap-10 lg:grid-cols-[1fr_1.2fr] lg:items-center"><div><p className="text-sm font-bold uppercase tracking-[0.18em] text-highlight">Trust comes first</p><h2 className="mt-3 text-4xl font-bold tracking-tight sm:text-5xl">Share with people, not strangers.</h2><p className="mt-5 max-w-xl leading-7 text-primary-foreground/70">Profiles, payments, messaging, and reviews work together so every exchange feels clear and accountable.</p></div><div className="grid gap-4 sm:grid-cols-3">{[[ShieldCheck,"Verified members","Know who you’re meeting."],[CircleDollarSign,"Secure payments","Protected, simple transactions."],[Star,"Community reviews","Real trust built over time."]].map(([Icon,title,copy]) => { const TrustIcon = Icon as typeof ShieldCheck; return <div key={String(title)} className="rounded-2xl bg-primary-foreground/8 p-5"><TrustIcon className="size-6 text-highlight" /><h3 className="mt-8 font-display text-lg font-bold">{String(title)}</h3><p className="mt-2 text-sm leading-6 text-primary-foreground/65">{String(copy)}</p></div>; })}</div></div></Container></Section>

    <Section><Container><div className="grid overflow-hidden rounded-[2rem] bg-highlight lg:grid-cols-2"><div className="p-8 sm:p-12 lg:p-16"><Leaf className="size-10 text-highlight-foreground" /><p className="mt-8 text-sm font-bold uppercase tracking-[0.18em] text-highlight-foreground/65">Your impact adds up</p><h2 className="mt-3 text-4xl font-bold text-highlight-foreground sm:text-5xl">Good for your wallet. Better for the planet.</h2><p className="mt-5 max-w-xl leading-7 text-highlight-foreground/75">Every borrowed item means one less rushed purchase, more value from things already made, and a stronger local network.</p><Button asChild className="mt-8" size="lg"><Link to="/impact-dashboard">Track your impact <ArrowRight /></Link></Button></div><div className="relative hidden min-h-[320px] items-center justify-center bg-highlight-foreground/5 p-12 lg:flex"><div className="grid grid-cols-2 gap-4 opacity-70">{[Leaf, CircleDollarSign, Heart, ShieldCheck].map((Icon, i) => <div key={i} className="grid size-28 place-items-center rounded-2xl bg-highlight-foreground/10"><Icon className="size-10 text-highlight-foreground/70" /></div>)}</div></div></div></Container></Section>

    <Section className="bg-card"><Container><div className="mx-auto max-w-3xl text-center"><p className="text-sm font-bold uppercase tracking-[0.18em] text-secondary">Community Feedback</p><h2 className="mt-3 font-display text-4xl font-bold tracking-tight sm:text-5xl">What Our Community Thinks</h2><p className="mt-5 leading-7 text-muted-foreground">Reviews from Flex My Stuff members will appear here.</p><div className="mt-12 grid gap-4 sm:grid-cols-3">{[0,1,2].map((i) => <div key={i} className="flex min-h-44 flex-col items-center justify-center gap-3 rounded-2xl border border-dashed border-border bg-muted/40 p-6 text-center"><MessageSquareQuote className="size-7 text-muted-foreground/50" /><p className="text-xs leading-5 text-muted-foreground/70">Awaiting member reviews</p></div>)}</div><div className="mt-10 flex flex-col items-center justify-center gap-3 sm:flex-row"><Button asChild variant="highlight" size="lg"><Link to="/community"><PencilLine /> Write a Review</Link></Button><Button asChild variant="outline" size="lg"><Link to="/how-it-works">Learn How Flexing Works <ArrowRight /></Link></Button></div></div></Container></Section>

    <footer className="border-t border-border bg-primary py-12 text-primary-foreground"><Container><div className="grid gap-10 sm:grid-cols-2 lg:grid-cols-4"><div><Link to="/" aria-label="Flex My Stuff home" className="inline-block rounded-xl focus-visible:outline-none focus-visible:ring-3 focus-visible:ring-highlight/50"><BrandLogo inverse className="h-20" /></Link><p className="mt-4 max-w-xs text-sm leading-6 text-primary-foreground/60">A more useful, connected, and sustainable neighborhood starts with sharing.</p></div><FooterLinks title="Discover" links={[["Explore","/explore"],["Categories","/categories"],["How it works","/how-it-works"]]} /><FooterLinks title="Community" links={[["Our community","/community"],["List an item","/add-listing"],["Your impact","/impact-dashboard"]]} /><div><p className="font-display font-bold">Start sharing</p><p className="mt-4 text-sm text-primary-foreground/60">Join neighbors making more of what’s already here.</p><Button asChild className="mt-5" variant="highlight"><Link to="/signup">Create an account</Link></Button></div></div><div className="mt-12 flex flex-col gap-3 border-t border-primary-foreground/15 pt-6 text-xs text-primary-foreground/50 sm:flex-row sm:justify-between"><p>© 2026 Flex My Stuff</p><p>Borrow more. Buy less. Live better.</p></div></Container></footer>
  </div>;
}

function SectionHeading({ eyebrow, title, link }: { eyebrow: string; title: string; link: "/explore" | "/categories" }) { return <div className="mb-9 grid grid-cols-[minmax(0,1fr)_auto] items-end gap-4"><div className="min-w-0"><p className="text-sm font-bold uppercase tracking-[0.18em] text-secondary">{eyebrow}</p><h2 className="mt-3 text-3xl font-bold tracking-tight sm:text-4xl">{title}</h2></div><Button asChild className="hidden sm:inline-flex" variant="ghost"><Link to={link}>View all <ArrowRight /></Link></Button></div>; }
function FooterLinks({ title, links }: { title: string; links: readonly [string, string][] }) { return <div><p className="font-display font-bold">{title}</p><ul className="mt-4 space-y-3">{links.map(([label, href]) => <li key={label}><a className="text-sm text-primary-foreground/60 transition-colors hover:text-highlight" href={href}>{label}</a></li>)}</ul></div>; }